version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        begins_with:
          match: ['add', 'Add', 'ADD']
      - do: dependent
        changed:
          file: 'CONTRIBUTORS.md'
          required: ['CONTRIBUTORS.md', .github/**.yml]
    pass:
      - do: comment
        payload:
          body: >
	    # :tada: Parabéns :tada:
              Você agora é membro da Community Dev Angola! :smile:
            Aceite o convite:
	    - Acessando o seu email
            ou
            - Clicando aqui [Community Dev Angola](https://github.com/Community-Dev-Angola)
      - do: merge
	merge_method: 'merge'
    # fail: # list of actions to be executed when at least one validation fails. Specify one or more. Omit this tag if no actions are needed.
      # - do: {{action}}
    # error: # list of actions to be executed when at least one validator throws an error. Specify one or more. Omit this tag if no actions are needed.
      # - do: {{action}}